### PR TITLE
PR-1 To-do-list - Display basic structure from object array

### PR DESCRIPTION
**Pull request by ivanmvh**
Project requirements.
-Set up a new project with webpack that is based on the webpack exercise you have already completed.
-Create an index.html file and write your HTML markup here. Create an empty To Do List placeholder (div or ul element). The index.html file must be set as a template using the HTML Webpack Plugin.
-Create an index.js file and set an array of some simple to do tasks (array of objects). Each task object should contain three keys:
>description [string].
>completed [bool].
>index: [number].
-Write a function to iterate over the tasks array and populate an HTML list item element for each task.
-On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
-Create a style.css and set rules for the To Do List. CSS must be loaded by Webpack Style/CSS Loader. Your list should be a clone of the part of the minimalist project captured in the video in the requirements. 
[](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

### CODE REVIEW

**Review by roshan-bajgain — COMMENTED** [review]
Hi @ivanmvh, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no README file. Please update the new README file. [Link](https://github.com/microverseinc/readme-template)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏a

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ivanmvh** [comment]
> Hi @ivanmvh,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has no README file. Please update the new README file. [Link](https://github.com/microverseinc/readme-template)
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏a
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

thanks

**Comment by ivanmvh** [comment]
Thanks you. I will change the readme.md file.

**Review by descholar-ceo — APPROVED** [review]
Hi @ivanmvh 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Implemented all requirements ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
